[project]
name = "instance"
requires-python = ">=3.14"
dynamic = ["version"]

authors = [
    { name = "Laura Thaci", email = "lthaci@tugraz.at" },
    { name = "Mojib Wali", email = "mojib.wali@tugraz.at" },
]

dependencies = [
    "invenio-app-rdm[opensearch2]==14.0.0rc2",
    "uwsgi>=2.0",
    "uwsgitop>=0.11",
    "uwsgi-tools>=1.1.1",
    "setuptools<82",
    "invenio-override[marc21,lom]>=1.0.0",
    "invenio-curations>=0.8.3",
    "invenio-global-search>=0.4.3",
    "invenio-records-global-search>=0.4.0",
    "invenio-records-marc21>=0.32.1",
    "invenio-records-lom>=0.23.0",
    "invenio-config-tugraz>=0.14.4",
]

[tool.djlint]
indent = 2
profile = "jinja"

[tool.setuptools]
py-modules = []

[tool.uv.sources]
invenio-override = { git = "https://github.com/tu-graz-library/invenio-override", branch = "main" }
invenio-config-tugraz = { git = "https://github.com/tu-graz-library/invenio-config-tugraz", branch = "repository" }