# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["build and push docker image"]
    types: [completed]
    branches: [main]
    tags: [v*]


jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest
          
    steps:

      - name: Get triggering workflow details
        run: |
          BRANCH_OR_TAG=${{ github.event.workflow_run.head_branch }}
          echo "BRANCH_OR_TAG=$BRANCH_OR_TAG" >> $GITHUB_ENV

      - name: Trigger gitlab pipeline
        uses: mb-wali/gitlab-cd-trigger@main
        with:
          URL: ${{ secrets.HOST }}
          GITLB_TRIGGER_TOKEN: ${{ secrets.GITLB_TRIGGER_TOKEN }}
          PROJECT_ID: 45464
          REF_NAME: 'main'
          PIPELINE_VARIABLES: '{"DOCKER_IMAGE_TAG":"${{ env.BRANCH_OR_TAG }}", "DOCKER_IMAGE_TAG_INSTANCE":"mug"}'
